## Working with employee Datasets

In [7]:
import pandas as pd

## Loading the datasets

In [10]:
data=pd.read_csv('Data_Sets/employee.csv')

## Viewing the dataframe

In [13]:
data.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
0,8724,Technology,region_26,Bachelors,m,sourcing,1,24,NaN,1,1,0,77
1,74430,HR,region_4,Bachelors,f,other,1,31,3.0,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelors,m,other,1,31,1.0,4,0,0,47
3,38562,Procurement,region_2,Bachelors,f,other,3,31,2.0,9,0,0,65
4,64486,Finance,region_29,Bachelors,m,sourcing,1,30,4.0,7,0,0,61

In [15]:
data.sample(5)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
13519,18489,Operations,region_22,Bachelors,m,other,1,44,4.0,14,1,0,60
13692,64672,Technology,region_13,Masters & above,f,other,1,41,3.0,9,1,0,78
4490,47992,Operations,region_13,Masters & above,m,sourcing,3,38,4.0,6,1,0,66
4777,63894,Operations,region_13,Bachelors,f,sourcing,1,38,2.0,3,0,0,63
14158,18799,Sales & Marketing,region_13,Bachelors,m,sourcing,1,40,1.0,14,0,0,51

In [17]:
data.tail()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
17412,64573,Technology,region_7,Bachelors,f,referred,2,30,5.0,6,1,0,81
17413,49584,HR,region_7,Bachelors,m,other,1,33,1.0,9,0,0,51
17414,49584,HR,region_7,Bachelors,m,other,1,33,1.0,9,0,0,51
17415,49584,HR,region_7,Bachelors,m,other,1,33,1.0,9,0,0,51
17416,64573,HR,region_7,Bachelors,f,referred,1,35,5.0,4,1,0,81

In [21]:
data.shape

(17417, 13)

In [27]:
data.columns

Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met_more_than_80', 'awards_won',
       'avg_training_score'],
      dtype='object')

In [29]:
# Get 5 random rows from the DataFrame
print(data.sample(5))

       employee_id         department     region        education gender  \
10621        65118            Finance  region_15        Bachelors      m
14316        70623          Analytics  region_34        Bachelors      m
4837         17288            Finance  region_28        Bachelors      m
16725        77344          Analytics  region_13        Bachelors      m
9088         62137  Sales & Marketing  region_22  Masters & above      m

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
10621               other                2   28                   3.0
14316            sourcing                1   33                   3.0
4837             sourcing                1   30                   3.0
16725            sourcing                2   30                   3.0
9088                other                1   34                   1.0

       length_of_service  KPIs_met_more_than_80  awards_won  \
10621                  3                      0           0
14316                  9                      0           0
4837                   7                      1           1
16725                  5                      0           0
9088                   4                      0           0

       avg_training_score
10621                  59
14316                  81
4837                   55
16725                  84
9088                   46

In [31]:
# Get a concise summary of Dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17417 entries, 0 to 17416
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            17417 non-null  int64
 1   department             17417 non-null  object
 2   region                 17417 non-null  object
 3   education              16646 non-null  object
 4   gender                 17417 non-null  object
 5   recruitment_channel    17417 non-null  object
 6   no_of_trainings        17417 non-null  int64
 7   age                    17417 non-null  int64
 8   previous_year_rating   16054 non-null  float64
 9   length_of_service      17417 non-null  int64
 10  KPIs_met_more_than_80  17417 non-null  int64
 11  awards_won             17417 non-null  int64
 12  avg_training_score     17417 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 1.7+ MB

In [35]:
# view the data types of all columns
print(data.dtypes)

employee_id                int64
department                object
region                    object
education                 object
gender                    object
recruitment_channel       object
no_of_trainings            int64
age                        int64
previous_year_rating     float64
length_of_service          int64
KPIs_met_more_than_80      int64
awards_won                 int64
avg_training_score         int64
dtype: object

In [39]:
# Get the numberof unique values for each column
print(data.nunique())

employee_id              17414
department                   9
region                      34
education                    3
gender                       2
recruitment_channel          3
no_of_trainings              9
age                         41
previous_year_rating         5
length_of_service           34
KPIs_met_more_than_80        2
awards_won                   2
avg_training_score          61
dtype: int64

In [41]:
# count unique values for a specific collumn
print(data.value_counts())

employee_id  department         region     education        gender  recruitment_channel  no_of_trainings  age  previous_year_rating  length_of_service  KPIs_met_more_than_80  awards_won  avg_training_score
49584        HR                 region_7   Bachelors        m       other                1                33   1.0                   9                  0                      0           51                    3
3            Procurement        region_22  Masters & above  f       other                1                38   5.0                   4                  1                      0           67                    1
52445        Sales & Marketing  region_1   Masters & above  m       other                1                37   5.0                   4                  1                      0           49                    1
52395        Operations         region_10  Masters & above  m       sourcing             1                37   5.0                   4                  1                      0           58                    1
52398        Sales & Marketing  region_19  Bachelors        m       sourcing             1                31   3.0                   3                  1                      0           50                    1
                                                                                                                                                                                                                ..
25734        Procurement        region_13  Bachelors        m       other                1                30   4.0                   5                  0                      0           71                    1
25736        Sales & Marketing  region_20  Bachelors        f       other                1                29   3.0                   2                  0                      0           44                    1
25738        Procurement        region_2   Masters & above  f       sourcing             3                36   3.0                   6                  1                      0           74                    1
25741        Procurement        region_16  Bachelors        f       sourcing             1                31   5.0                   7                  1                      0           73                    1
78295        Sales & Marketing  region_14  Bachelors        f       sourcing             1                36   3.0                   5                  0                      0           48                    1
Name: count, Length: 15422, dtype: int64

In [43]:
data.describe()

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
count,17417.000000,17417.000000,17417.000000,16054.000000,17417.000000,17417.000000,17417.000000,17417.000000
mean,39083.491129,1.250732,34.807774,3.345459,5.801860,0.358845,0.023368,63.176322
std,22707.024087,0.595692,7.694046,1.265386,4.175533,0.479675,0.151074,13.418179
min,3.000000,1.000000,20.000000,1.000000,1.000000,0.000000,0.000000,39.000000
25%,19281.000000,1.000000,29.000000,3.000000,3.000000,0.000000,0.000000,51.000000
50%,39122.000000,1.000000,33.000000,3.000000,5.000000,0.000000,0.000000,60.000000
75%,58838.000000,1.000000,39.000000,4.000000,7.000000,1.000000,0.000000,75.000000
max,78295.000000,9.000000,60.000000,5.000000,34.000000,1.000000,1.000000,99.000000

In [49]:
# numerical + categorical
data.describe(include='all')

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
count,17417.000000,17417,17417,16646,17417,17417,17417.000000,17417.000000,16054.000000,17417.000000,17417.000000,17417.000000,17417.000000
unique,NaN,9,34,3,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Sales & Marketing,region_2,Bachelors,m,other,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,5458,3918,11519,12314,9751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,39083.491129,NaN,NaN,NaN,NaN,NaN,1.250732,34.807774,3.345459,5.801860,0.358845,0.023368,63.176322
std,22707.024087,NaN,NaN,NaN,NaN,NaN,0.595692,7.694046,1.265386,4.175533,0.479675,0.151074,13.418179
min,3.000000,NaN,NaN,NaN,NaN,NaN,1.000000,20.000000,1.000000,1.000000,0.000000,0.000000,39.000000
25%,19281.000000,NaN,NaN,NaN,NaN,NaN,1.000000,29.000000,3.000000,3.000000,0.000000,0.000000,51.000000
50%,39122.000000,NaN,NaN,NaN,NaN,NaN,1.000000,33.000000,3.000000,5.000000,0.000000,0.000000,60.000000
75%,58838.000000,NaN,NaN,NaN,NaN,NaN,1.000000,39.000000,4.000000,7.000000,1.000000,0.000000,75.000000
max,78295.000000,NaN,NaN,NaN,NaN,NaN,9.000000,60.000000,5.000000,34.000000,1.000000,1.000000,99.000000

In [51]:
# view memory usage of each column
print(data.memory_usage())

Index                       132
employee_id              139336
department               139336
region                   139336
education                139336
gender                   139336
recruitment_channel      139336
no_of_trainings          139336
age                      139336
previous_year_rating     139336
length_of_service        139336
KPIs_met_more_than_80    139336
awards_won               139336
avg_training_score       139336
dtype: int64

## Check for the missing values

In [54]:
data.isnull().sum()

employee_id                 0
department                  0
region                      0
education                 771
gender                      0
recruitment_channel         0
no_of_trainings             0
age                         0
previous_year_rating     1363
length_of_service           0
KPIs_met_more_than_80       0
awards_won                  0
avg_training_score          0
dtype: int64

In [58]:
data['education'].isnull().sum()
data['education'].head(60)

0           Bachelors
1           Bachelors
2           Bachelors
3           Bachelors
4           Bachelors
5           Bachelors
6           Bachelors
7           Bachelors
8     Masters & above
9           Bachelors
10          Bachelors
11    Masters & above
12    Masters & above
13          Bachelors
14          Bachelors
15          Bachelors
16          Bachelors
17          Bachelors
18          Bachelors
19          Bachelors
20    Masters & above
21          Bachelors
22    Masters & above
23    Masters & above
24          Bachelors
25          Bachelors
26    Masters & above
27          Bachelors
28          Bachelors
29          Bachelors
30    Masters & above
31          Bachelors
32          Bachelors
33          Bachelors
34    Masters & above
35          Bachelors
36    Masters & above
37          Bachelors
38          Bachelors
39          Bachelors
40          Bachelors
41          Bachelors
42          Bachelors
43          Bachelors
44          Bachelors
45          Bachelors
46          Bachelors
47    Masters & above
48          Bachelors
49                NaN
50    Masters & above
51          Bachelors
52          Bachelors
53    Below Secondary
54          Bachelors
55    Masters & above
56          Bachelors
57    Masters & above
58          Bachelors
59          Bachelors
Name: education, dtype: object

In [66]:
# Check for missing values in each column
missing_data = data.isnull().sum()

# Calculate the percentage of missing values
missing_percentage = (missing_data/len(data)) * 100

# Combine missing data count and missing percentage
missing_info = pd.DataFrame({
     'Missing Values': missing_data,
     'Missing Percentage': missing_percentage
 })

#Filter columns with missing data
missing_info = missing_info[missing_info['Missing Values'] > 0]

# Format the 'Missing Percentage' column to add a '%' symbol
missing_info['Missing Percentage'] = missing_info['Missing Percentage'].apply(lambda x: f"{x:.2f}%")

# Display the columns with missing data and their percentage
print(missing_info)

                      Missing Values Missing Percentage
education                        771              4.43%
previous_year_rating            1363              7.83%

In [68]:
# Check unique values in the 'education' and 'previous_year_rating' columns
education_unique_values = data['education'].unique()
previous_rate_rating_unique_values = data['previous_year_rating'].unique()

print("Unique values in 'education':", education_unique_values)
print("Unique values in 'previous_year_rating':", previous_rate_rating_unique_values)

Unique values in 'education': ['Bachelors' 'Masters & above' nan 'Below Secondary']
Unique values in 'previous_year_rating': [nan  3.  1.  2.  4.  5.]

In [72]:
# Check the data types of column with missing values
missing_columns = data.columns[data.isnull().any()]
missing_data_types = data[missing_columns].dtypes

print("\nData types of columns with missing values:")
print(missing_data_types)

Data types of columns with missing values:
education                object
previous_year_rating    float64
dtype: object

In [76]:
data['education'].mode()[0]

'Bachelors'

In [78]:
data['education'].value_counts()

education
Bachelors          11519
Masters & above     4841
Below Secondary      286
Name: count, dtype: int64

In [80]:
data['previous_year_rating'].mean()

3.3454590756197833

In [82]:
data['previous_year_rating'].median()

3.0

In [86]:
# Identify numeric and categorical columns
numeric_columns = data.select_dtypes(include=['float64','int64']).columns
categorical_columns = data.select_dtypes(include=['object','category']).columns

In [90]:
print(numeric_columns)

Index(['employee_id', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met_more_than_80', 'awards_won',
       'avg_training_score'],
      dtype='object')

In [92]:
print(categorical_columns)

Index(['department', 'region', 'education', 'gender', 'recruitment_channel'], dtype='object')

In [98]:
# Fill missing values for numeric columns withe the mean
data[numeric_columns] = data[numeric_columns].fillna(data[numeric_columns].mean())

# Fill missing values for categorical columns with the mode
for col in categorical_columns:
    data[col] = data[col].fillna(data[col].mode()[0])

# Display the DataFrame after filling missing values
df=data.head()

In [100]:
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
0,8724,Technology,region_26,Bachelors,m,sourcing,1,24,3.345459,1,1,0,77
1,74430,HR,region_4,Bachelors,f,other,1,31,3.000000,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelors,m,other,1,31,1.000000,4,0,0,47
3,38562,Procurement,region_2,Bachelors,f,other,3,31,2.000000,9,0,0,65
4,64486,Finance,region_29,Bachelors,m,sourcing,1,30,4.000000,7,0,0,61

In [102]:
df['education'].isnull().sum()

0

In [104]:
df['previous_year_rating'].isnull().sum()

0

In [110]:
pd.set_option('display.max_rows',None)

In [112]:
pd.set_option('display.max_rows', None)
df['previous_year_rating'].isnull().sum()

0

In [116]:
# Convert columns to the specified data types

df['employee_id'] = df['employee_id'].astype('int64')
df['department'] = df['department'].astype('object')
df['region'] = df['region'].astype('object')
df['education'] = df['education'].astype('object')
df['gender'] = df['gender'].astype('object')
df['recruitment_channel'] = df['recruitment_channel'].astype('object')
df['no_of_trainings'] = df['no_of_trainings'].astype('int64')
df['age'] = df['age'].astype('int64')
df['previous_year_rating'] = df['previous_year_rating'].astype('float64')
df['length_of_service'] = df['length_of_service'].astype('int64')
df['KPIs_met_more_than_80'] = df['KPIs_met_more_than_80'].astype('int64')
df['awards_won'] = df['awards_won'].astype('int64')
df['avg_training_score'] = df['avg_training_score'].astype('int64')

# Display the data types after conversion
print(df.dtypes)

employee_id                int64
department                object
region                    object
education                 object
gender                    object
recruitment_channel       object
no_of_trainings            int64
age                        int64
previous_year_rating     float64
length_of_service          int64
KPIs_met_more_than_80      int64
awards_won                 int64
avg_training_score         int64
dtype: object

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['employee_id'] = df['employee_id'].astype('int64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['department'] = df['department'].astype('object')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region'] = df['region'].astype('object')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['education'] = df['education'].astype('object')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].astype('object')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['recruitment_channel'] = df['recruitment_channel'].astype('object')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['no_of_trainings'] = df['no_of_trainings'].astype('int64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].astype('int64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['previous_year_rating'] = df['previous_year_rating'].astype('float64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['length_of_service'] = df['length_of_service'].astype('int64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['KPIs_met_more_than_80'] = df['KPIs_met_more_than_80'].astype('int64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['awards_won'] = df['awards_won'].astype('int64')
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14324\1162295304.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_training_score'] = df['avg_training_score'].astype('int64')

In [126]:
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score
0,8724,Technology,region_26,Bachelors,m,sourcing,1,24,3.345459,1,1,0,77
1,74430,HR,region_4,Bachelors,f,other,1,31,3.000000,5,0,0,51
2,72255,Sales & Marketing,region_13,Bachelors,m,other,1,31,1.000000,4,0,0,47
3,38562,Procurement,region_2,Bachelors,f,other,3,31,2.000000,9,0,0,65
4,64486,Finance,region_29,Bachelors,m,sourcing,1,30,4.000000,7,0,0,61

In [128]:
# Check for duplicates
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Remove duplicate rows if any
df = df.drop_duplicates()

#Display the DataFrame after removing duplicated
print(df.head())

Number of duplicate rows: 0
   employee_id         department     region  education gender  \
0         8724         Technology  region_26  Bachelors      m
1        74430                 HR   region_4  Bachelors      f
2        72255  Sales & Marketing  region_13  Bachelors      m
3        38562        Procurement   region_2  Bachelors      f
4        64486            Finance  region_29  Bachelors      m

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24              3.345459
1               other                1   31              3.000000
2               other                1   31              1.000000
3               other                3   31              2.000000
4            sourcing                1   30              4.000000

   length_of_service  KPIs_met_more_than_80  awards_won  avg_training_score
0                  1                      1           0                  77
1                  5                      0           0                  51
2                  4                      0           0                  47
3                  9                      0           0                  65
4                  7                      0           0                  61

# Lambda Functions in Python

In [131]:
add = lambda x,y: x+y
print(add(1,2))

3

In [137]:
num = [1,2,3,4]
square = map(lambda x:x*2, num)
print(list(square))

[2, 4, 6, 8]

In [139]:
num = [1,2,3,4]
even = filter(lambda x:x%2==0, num)
print(list(even))

[2, 4]

# Map and Filter

In [142]:
# 1. Add 'age_group' column based on 'age'

def age_group(age):
    if age < 30:
        return 'Youth'
    elif 30 <= age < 50:
        return 'Middle-Aged'
    else:
        return 'senior'

df['age_group'] = df['age'].apply(age_group)

In [150]:
df[['age_group','age']].head()

     age_group  age
0        Youth   24
1  Middle-Aged   31
2  Middle-Aged   31
3  Middle-Aged   31
4  Middle-Aged   30

In [156]:
# 2. Add 'years_at_company'column based on 'length_of_service'

df['years_at_company'] = df['length_of_service']

In [169]:
# 3. Add 'training_score_category' column based on 'avg_training_score'
def training_score_category(score):
    if score < 50:
        return 'low'
    elif score <= score < 75:
        return 'Medium'
    else:
        return 'High'

df['training_score_category'] = df['avg_training_score'].apply(training_score_category)
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score,age_group,years_at_company,training_score_category,performance
0,8724,Technology,region_26,Bachelors,m,sourcing,1,24,3.345459,1,1,0,77,Youth,1,High,Good
1,74430,HR,region_4,Bachelors,f,other,1,31,3.000000,5,0,0,51,Middle-Aged,5,Medium,Good
2,72255,Sales & Marketing,region_13,Bachelors,m,other,1,31,1.000000,4,0,0,47,Middle-Aged,4,low,Needs Improvement
3,38562,Procurement,region_2,Bachelors,f,other,3,31,2.000000,9,0,0,65,Middle-Aged,9,Medium,Needs Improvement
4,64486,Finance,region_29,Bachelors,m,sourcing,1,30,4.000000,7,0,0,61,Middle-Aged,7,Medium,Excellent

In [171]:
# 4. Add 'performance column based on 'previous_year_rating'
def performance_rating(rating):
    if rating >=4.0:
        return 'Excellent'
    elif 3.0 <= rating < 4.0:
        return 'Good'
    else:
        return 'Needs Improvement'

df['performance'] =df['previous_year_rating'].apply(performance_rating)
df.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met_more_than_80,awards_won,avg_training_score,age_group,years_at_company,training_score_category,performance
0,8724,Technology,region_26,Bachelors,m,sourcing,1,24,3.345459,1,1,0,77,Youth,1,High,Good
1,74430,HR,region_4,Bachelors,f,other,1,31,3.000000,5,0,0,51,Middle-Aged,5,Medium,Good
2,72255,Sales & Marketing,region_13,Bachelors,m,other,1,31,1.000000,4,0,0,47,Middle-Aged,4,low,Needs Improvement
3,38562,Procurement,region_2,Bachelors,f,other,3,31,2.000000,9,0,0,65,Middle-Aged,9,Medium,Needs Improvement
4,64486,Finance,region_29,Bachelors,m,sourcing,1,30,4.000000,7,0,0,61,Middle-Aged,7,Medium,Excellent

In [173]:
# 5. Add 'awards_received column based on 'awards_won'
df['awards_received'] = df['awards_won'].apply(lambda x: True if x > 0 else False)
print(df.head())

   employee_id         department     region  education gender  \
0         8724         Technology  region_26  Bachelors      m
1        74430                 HR   region_4  Bachelors      f
2        72255  Sales & Marketing  region_13  Bachelors      m
3        38562        Procurement   region_2  Bachelors      f
4        64486            Finance  region_29  Bachelors      m

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24              3.345459
1               other                1   31              3.000000
2               other                1   31              1.000000
3               other                3   31              2.000000
4            sourcing                1   30              4.000000

   length_of_service  KPIs_met_more_than_80  awards_won  avg_training_score  \
0                  1                      1           0                  77
1                  5                      0           0                  51
2                  4                      0           0                  47
3                  9                      0           0                  65
4                  7                      0           0                  61

     age_group  years_at_company training_score_category        performance  \
0        Youth                 1                    High               Good
1  Middle-Aged                 5                  Medium               Good
2  Middle-Aged                 4                     low  Needs Improvement
3  Middle-Aged                 9                  Medium  Needs Improvement
4  Middle-Aged                 7                  Medium          Excellent

   awards_received
0            False
1            False
2            False
3            False
4            False

# New Feature Engineering

In [182]:
# Assuming df is already loaded and missing values have been filled

# 1. age_and_servie: Adds the age and length of service to create a combined feature
df['age_and_service'] = df['age'] + df['length_of_service'] #Combined age and serviec to reflect overall experience

# 2. training_efficiency: Measures how efficient an employee is in terms of training
df['training_efficiency'] = df['avg_training_score']/df['no_of_trainings'] # how well the employees perform

#3. service_to_training_ratio: ratio of servie yeard to the number of trainings attended
df['service_to_training_ratio'] = df['length_of_service']/df['no_of_trainings'] # provides insights into training intensity

# 4. age_servie_interaction: Interaction term between age and years of experience
df['age_servie_interaction'] = df['age'] * df['length_of_service'] # This can uncover patterns of employees who have been long

# 5. experience_in_years: Calculates the total experience in years based on the length of service in months
df['experience_in_years'] = df['length_of_service'] / 12

# 6. education_level: Binary feature indcating if an employee had a Master's or PhD
df['education_level'] = df['education'].apply(lambda x: 1 if x in ['Masters', 'PhD'] else 0) 

# 7.re

# 8. is_young_employee: Binary Column marking emplouees who are under 30 years old
df['is_young_employee'] = df['age'].apply(lambda x: 1 if x <30 else 0) # flags employees under 30 years of age

# 9. is_experienced_employee: Binary column marking employees with more than 5 years of service
df['is_experienced_employee'] = df['length_of_service'].apply(lambda x: 1 if x > 5 else 0) #flags employee withmore than 5

#  10. employee_tenure_in_months: Converts length of service into months to reflect tenure in more granular detail
df['employee_tenure_in_months']  = df['length_of_service'] * 12   # converts years to months, showing exact months of employment

# 11. age_times_performance: Combines age and performance to find any relationship between age and performance ratings
df['age_times_performancce'] = df['age'] * df['previous_year_rating'] #multiplies age by performance to explore if age correlate

# 12. service_category: categorizes employee into short-term, medium-term and long-term based on yeard of service
def service_category(years):
    if years < 2:
        return 'Short Term'
    elif 2<= years <= 5:
        return 'Medium Term'
    else:
        return 'Long Term'

df['service_category'] = df['length_of_service'].apply(service_category) # Categories employeed into service periods

# 13. age_category_by_service: Creates a category combining age and years of service for segmentation
def age_service_category(row):
    if row['age'] < 30 and row['length_of_service'] < 2:
        return 'Young Short-term'
    elif row['age'] >= 30 and row['length_of_service'] < 5:
        return 'Mid-age Medium-term'
    elif row['age'] >= 40 and row['length_of_service'] > 5:
        return 'Experienced Long-term'
    else:
        return 'Other'

df['age_category_by_service'] = df.apply(age_service_category, axis=1) # Combines age and service Length

#Show the updated DataFrame
print(df.head())

   employee_id         department     region  education gender  \
0         8724         Technology  region_26  Bachelors      m
1        74430                 HR   region_4  Bachelors      f
2        72255  Sales & Marketing  region_13  Bachelors      m
3        38562        Procurement   region_2  Bachelors      f
4        64486            Finance  region_29  Bachelors      m

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24              3.345459
1               other                1   31              3.000000
2               other                1   31              1.000000
3               other                3   31              2.000000
4            sourcing                1   30              4.000000

   length_of_service  ...  service_to_training_ratio  age_servie_interaction  \
0                  1  ...                        1.0                      24
1                  5  ...                        5.0                     155
2                  4  ...                        4.0                     124
3                  9  ...                        3.0                     279
4                  7  ...                        7.0                     210

   experience_in_years education_level  is_young_employee  \
0             0.083333               0                  1
1             0.416667               0                  0
2             0.333333               0                  0
3             0.750000               0                  0
4             0.583333               0                  0

  is_experienced_employee employee_tenure_in_months  age_times_performancce  \
0                       0                        12               80.291018
1                       0                        60               93.000000
2                       0                        48               31.000000
3                       1                       108               62.000000
4                       1                        84              120.000000

   service_category  age_category_by_service
0        Short Term         Young Short-term
1       Medium Term                    Other
2       Medium Term      Mid-age Medium-term
3         Long Term                    Other
4         Long Term                    Other

[5 rows x 30 columns]

In [194]:
datas = pd.read_csv('Data_Sets/used_cars.csv', sep = ';')

In [196]:
datas

              brand                                              model  \
0              Ford                    Utility Police Interceptor Base
1           Hyundai                                       Palisade SEL
2             Lexus                                      RX 350 RX 350
3          INFINITI                                   Q50 Hybrid Sport
4              Audi                          Q3 45 S line Premium Plus
5             Acura                                           ILX 2.4L
6              Audi                               S3 2.0T Premium Plus
7               BMW                                             740 iL
8             Lexus                                     RC 350 F Sport
9             Tesla                            Model X Long Range Plus
10             Land       Rover Range Rover Sport 3.0 Supercharged HST
11            Aston                            Martin DBS Superleggera
12           Toyota                                  Supra 3.0 Premium
13          Lincoln                                Aviator Reserve AWD
14           Jaguar                                             F-TYPE
15             Land                                      Rover LR4 HSE
16    Mercedes-Benz                                        Metris Base
17            Dodge                                     Challenger SXT
18           Nissan                                    350Z Enthusiast
19           Jaguar                                           F-TYPE R
20          Genesis                                    GV70 3.5T Sport
21        Chevrolet                                            S-10 LS
22              BMW                         440 Gran Coupe 440i xDrive
23             Ford                                          F-150 XLT
24        Chevrolet                                       Suburban RST
25          Hyundai                                     Elantra N Base
26           Nissan                                          Sentra SR
27    Mercedes-Benz                             AMG CLA 45 Base 4MATIC
28              BMW                            650 Gran Coupe i xDrive
29             Audi                               Q5 2.0T Premium Plus
30    Mercedes-Benz                               AMG C 43 Base 4MATIC
31            Dodge                          Ram 1500 Laramie Mega Cab
32              BMW                          i3 120Ah w/Range Extender
33              Kia                                         Sorento SX
34            Lexus                                        LX 570 Base
35             Jeep                              New Compass Trailhawk
36              BMW                                              340 i
37             Audi                       A4 2.0T Premium Plus quattro
38          Hyundai                                          Tucson SE
39              BMW                                       Z4 sDrive28i
40          Bentley                               Continental GTC Base
41            Honda                                     Passport Elite
42            Dodge                                      Sprinter 2500
43              BMW                                      M850 i xDrive
44            Lucid                                  Air Grand Touring
45             Audi                                         A7 Premium
46        Chevrolet                   Silverado 1500 Custom Trail Boss
47             MINI                      Convertible John Cooper Works
48           Toyota                                     Avalon Touring
49          Porsche                           Cayenne Platinum Edition
50    Mercedes-Benz                                         AMG C 63 S
51            Honda                                          CR-V EX-L
52           Hummer                                            H2 Base
53          Porsche                                      911 Carrera S
54    Mercedes-Benz                                  CLA-Class CLA 250
55         Chrysler                                        300 Touring
56           Nissan                                           Rogue SV
57             Audi                                            A3 2.0T
58             Ford                                 Mustang GT Premium
59            Acura                                      RL Technology
60            Volvo                            XC90 Hybrid T8 R-Design
61             Audi                                         R8 5.2 V10
62    Mercedes-Benz                                  GLK-Class GLK 350
63           Toyota                                            C-HR LE
64            Lexus                                        IS 350 Base
65              BMW                                            X4 M40i
66              BMW                                              M4 CS
67         Cadillac                                 CT5 Premium Luxury
68            Lucid                                  Air Grand Touring
69             Audi                               A5 2.0T Premium Plus
70         Chrysler                                          300C SRT8
71          Bentley                                 Continental GT W12
72              BMW                                            M4 Base
73           Toyota                         GR Corolla Circuit Edition
74             Audi                                          RS 5 2.9T
75          Porsche                                       Cayenne Base
76      Lamborghini                              Huracan Tecnica Coupe
77         Maserati                                     Quattroporte S
78           Jaguar                                     XF 35t R-Sport
79            Lexus                                        ES 330 Base
80             Land                 Rover Discovery Sport SE R-Dynamic
81          Porsche                                         Cayman GTS
82          Genesis                                   G90 3.3T Premium
83       Volkswagen                    Golf R 20th Anniversary Edition
84          Hyundai                              Sonata Hybrid Limited
85             Audi                                 RS 7 4.0T Prestige
86              BMW                                             740 Li
87    Mercedes-Benz                                GLS 450 Base 4MATIC
88              BMW                                            M6 Base
89           Subaru                                     Forester 2.5 X
90          Hyundai                                     Elantra N Base
91              Kia                     Niro Plug-In Hybrid EX Premium
92           Rivian                              R1S Adventure Package
93            Aston                            Martin DBS Superleggera
94    Mercedes-Benz                                       SLC 300 Base
95              BMW                                   435 Gran Coupe i
96             Jeep                              Grand Cherokee Summit
97            Lexus                                        RC 350 Base
98              BMW                                              525 i
99           Toyota                                         Corolla LE
100        Cadillac                                    CT5-V Blackwing
101             GMC                                       Acadia SLT-1
102           Lexus                                        LC 500 Base
103             BMW                                            i8 Base
104           Lexus                                       ES 300h Base
105        Cadillac                                     CT5-V V-Series
106             BMW                                       540 i xDrive
107       Chevrolet                              Express 1500 Work Van
108            Jeep                                  Gladiator Rubicon
109             BMW                                       Z4 sDrive28i
110            Land                 Rover LR4 HSE LUX Landmark Edition
111        Cadillac                                          XT4 Sport
112             BMW                                    750 750i xDrive
113         Bentley                                           Arnage R
114         Lincoln                                Aviator Reserve AWD
115   Mercedes-Benz                            AMG GL AMG GL 63 4MATIC
116             RAM                           ProMaster 3500 High Roof
117            Ford                    Utility Police Interceptor Base
118            Audi                                    A5 2.0T Premium
119          Nissan                                       GT-R Premium
120            Land      Rover Range Rover Sport 3.0L Supercharged HSE
121          Toyota                                         Corolla LE
122          Rivian                              R1S Adventure Package
123   Mercedes-Benz                                C-Class C300 4MATIC
124         Porsche                                 Cayenne E-Hybrid S
125       Chevrolet                              Express 1500 Work Van
126        INFINITI                                          Q70h Base
127            Audi                                    A7 Premium Plus
128            Audi                               Q7 3.0T Premium Plus
129           Lucid                                           Air Pure
130        Chrysler                                   Pacifica Touring
131            Audi                              TTS 2.0T Premium Plus
132             BMW                            650 Gran Coupe i xDrive
133          Subaru                                   Forester Premium
134   Mercedes-Benz                                     AMG C AMG C 63
135            Land                                      Rover LR3 HSE
136             BMW                                       X7 xDrive40i
137            Ford                                Transit Connect XLT
138           Lexus                                   LX 570 Three-Row
139         Porsche                                      911 Carrera S
140           Dodge                          Ram 2500 Laramie Quad Cab
141          Nissan                                          Armada SL
142         Porsche                                        Cayman Base
143   Mercedes-Benz                                    GLE 450 GLE 450
144       Chevrolet                                     Monte Carlo SS
145             BMW                                            M5 Base
146         Hyundai                                        Kona N Base
147       Chevrolet                                     Monte Carlo SS
148            Land                      Rover Range Rover Evoque Pure
149            Audi                               S7 4.0T Premium Plus
150             GMC                                       Acadia SLT-1
151            Alfa                             Romeo Stelvio Ti Sport
152         Ferrari                                            FF Base
153             Kia                                          K900 5.0L
154            Ford                                           E150 XLT
155           Tesla                                Model 3 Performance
156          Toyota                                        4Runner SR5
157          Subaru                                      Forester Base
158         Porsche                                         Panamera 2
159          Toyota                                   Tacoma PreRunner
160             RAM                                       2500 Laramie
161             Kia                                 Sportage Nightfall
162        Cadillac                                           DTS Base
163          Toyota                                  Land Cruiser Base
164          Nissan                                       GT-R Premium
165           Lexus                            NX 350 F SPORT Handling
166            Audi                                 Q7 45 Premium Plus
167           Lexus                                        LX 470 Base
168             GMC                                        Terrain SLE
169            Ford                                     Escape Limited
170           Lexus                                           LS 460 L
171            Ford                                Expedition Platinum
172       Chevrolet                                         Malibu LTZ
173            Audi                                  RS 7 4.0T quattro
174            Audi                               A5 2.0T Premium Plus
175         Genesis                                           G70 2.0T
176       Chevrolet                                     Trailblazer LS
177           Scion                                            tC Base
178         Lincoln                                    MKZ Hybrid Base
179            Ford                                     Transit-350 XL
180         Porsche                                         911 GT2 RS
181            Ford                                Explorer Timberline
182           Volvo                                           XC90 3.2
183       Chevrolet                                      Avalanche LTZ
184            Audi                                         TT RS 2.5T
185         Lincoln                                        Navigator L
186         Hyundai                                        Elantra GLS
187            Audi                              SQ5 3.0T Premium Plus
188      Mitsubishi                               Lancer Evolution GSR
189           Tesla                                Model Y Performance
190   Mercedes-Benz                                    Maybach S S 600
191          Nissan                                       GT-R Premium
192   Mercedes-Benz                                GLS 550 Base 4MATIC
193       Chevrolet                                     Blazer Premier
194           Mazda                                 CX-9 Grand Touring
195            Ford                             Expedition Max Limited
196          Nissan                                        Titan XD SV
197           Lexus                                   LX 570 Three-Row
198       Chevrolet                                   Traverse Premier
199   Mercedes-Benz                                 Sprinter High Roof
200             BMW                                            X5 3.0i
201            Ford                                          Fusion SE
202         Lincoln                                           MKZ Base
203            Ford                                                 GT
204         Genesis                                   G90 5.0 Ultimate
205           Lexus                                        LC 500 Base
206            Ford                                  Shelby GT500 Base
207          Saturn                                           Sky Base
208            Audi                                 RS Q8 4.0T quattro
209          Toyota                                       Land Cruiser
210   Mercedes-Benz                                    SL-Class SL 550
211         Porsche                                    911 Carrera C2S
212   Mercedes-Benz                             AMG GLA 45 Base 4MATIC
213            Ford                                   Taurus X Limited
214             BMW                                   440 Gran Coupe i
215           Honda                                           S2000 CR
216           Acura                      Integra w/A-Spec Tech Package
217            Ford                                  Excursion Limited
218   Mercedes-Benz                            SL-Class SL500 Roadster
219   Mercedes-Benz                                  CLS-Class CLS 550
220        INFINITI                                          G35 Sport
221      Volkswagen                             Golf GTI 2.0T S 4-Door
222           Dodge                           Challenger R/T Scat Pack
223         Lincoln                                Navigator L Reserve
224        Maserati                                        Ghibli S Q4
225           Tesla                                       Model X Base
226   Mercedes-Benz                                      AMG G 63 Base
227            Ford                                 Expedition Limited
228      Volkswagen                                          Routan SE
229         Bugatti                            Veyron 16.4 Grand Sport
230          Toyota                                     Highlander XLE
231           Honda                                           Civic LX
232            Jeep                          Wrangler Unlimited Sahara
233            Land                     Rover Range Rover Supercharged
234           Acura                         ILX 2.0L w/Premium Package
235             BMW                                            M6 Base
236        Polestar                                   2 Launch Edition
237             BMW                                       X6 sDrive35i
238         Porsche                                           Cayman S
239         Lincoln                              Corsair Grand Touring
240        Cadillac                                      DTS Luxury II
241        Cadillac                                    ATS 3.6L Luxury
242             GMC                                    Sierra 1500 SLT
243        INFINITI                                              G37 x
244            Ford                                    Transit-350 XLT
245        Cadillac                                         XTS Luxury
246          Nissan                       NV Passenger NV3500 HD SL V8
247   Mercedes-Benz                                GLS 450 Base 4MATIC
248          Toyota                                  Land Cruiser Base
249          Toyota                                  Land Cruiser Base
250             RAM                ProMaster 2500 Window Van High Roof
251     Lamborghini                                      Gallardo Base
252         Lincoln                                           MKZ Base
253   Mercedes-Benz                                     EQS 450 4MATIC
254     Lamborghini                              Huracan Tecnica Coupe
255            Alfa                          Romeo Giulia Quadrifoglio
256       Chevrolet                                     Trailblazer LT
257          Toyota                                  Land Cruiser Base
258     Lamborghini                                          Urus Base
259        INFINITI                                              G37 x
260        Maserati                                          Levante S
261          Toyota                                 Highlander Limited
262          Nissan                                          Armada SL
263            Audi                                         Q5 Premium
264            Ford                                  Shelby GT500 Base
265         Lincoln                                Navigator L Reserve
266   Mercedes-Benz                                      EQS 450+ Base
267             RAM                                       1500 Laramie
268         Lincoln                                      Town Car Base
269           Acura                               TLX w/A-Spec Package
270          Toyota                                    Camry Hybrid LE
271           Honda                                            CR-V EX
272   Mercedes-Benz                                      E-Class E 550
273           Mazda                           MX-5 Miata Grand Touring
274         Porsche                                   718 Boxster Base
275            Ford                                    Transit-350 XLT
276             Kia                                  Sportage SX Turbo
277        INFINITI                                        G37 S Sport
278          Nissan                                         Titan XD S
279            Audi                                   S7 2.9T Prestige

In [198]:
datas.shape

(4009, 12)

## Working with Used_Cars datasets

In [71]:
import pandas as pd
data = pd.read_csv('Data_Sets/used_cars.csv', sep=';')
data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

import os

directory = 'Data_Sets'
filename = 'used_cars.csv'

file_path = os.path.join(directory, filename)

data1=pd.read_csv(file_path)
data1.head()

In [73]:
data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [75]:
print(data['milage'])

0       51,000 mi.
1       34,742 mi.
2       22,372 mi.
3       88,900 mi.
4        9,835 mi.
           ...
4004       714 mi.
4005    10,900 mi.
4006     2,116 mi.
4007    33,000 mi.
4008    43,000 mi.
Name: milage, Length: 4009, dtype: object

In [77]:
data['milage'] = data['milage'].str.replace('mi.','',regex=False)

In [79]:
data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [81]:
data['milage'].dtype

dtype('O')

In [83]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int64(1), object(11)
memory usage: 376.0+ KB

In [87]:
data['milage']

0       51,000
1       34,742
2       22,372
3       88,900
4        9,835
         ...
4004       714
4005    10,900
4006     2,116
4007    33,000
4008    43,000
Name: milage, Length: 4009, dtype: object

In [89]:
data['milage'] = data['milage'].str.replace(',','',regex=False)

In [91]:
data['milage']

0       51000
1       34742
2       22372
3       88900
4        9835
         ...
4004      714
4005    10900
4006     2116
4007    33000
4008    43000
Name: milage, Length: 4009, dtype: object

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   object
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int64(1), object(11)
memory usage: 376.0+ KB

In [111]:
data['milage']=data['milage'].astype(int)

In [113]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   object
 1   model         4009 non-null   object
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   int32
 4   fuel_type     3839 non-null   object
 5   engine        4009 non-null   object
 6   transmission  4009 non-null   object
 7   ext_col       4009 non-null   object
 8   int_col       4009 non-null   object
 9   accident      3896 non-null   object
 10  clean_title   3413 non-null   object
 11  price         4009 non-null   object
dtypes: int32(1), int64(1), object(10)
memory usage: 360.3+ KB

In [117]:
import re

# Extract engine capacity
data['capacity'] = data['engine'].str.extract(r'(\d+\.\d+L|\d+L)')  # r = raw literals ("\" => literal)

# Display the updated dictionary with the new 'capacity' column
print(data.head())

      brand                            model  model_year  milage  \
0      Ford  Utility Police Interceptor Base        2013   51000
1   Hyundai                     Palisade SEL        2021   34742
2     Lexus                    RX 350 RX 350        2022   22372
3  INFINITI                 Q50 Hybrid Sport        2015   88900
4      Audi        Q3 45 S line Premium Plus        2021    9835

       fuel_type                                             engine  \
0  E85 Flex Fuel  300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...
1       Gasoline                               3.8L V6 24V GDI DOHC
2       Gasoline                                     3.5 Liter DOHC
3         Hybrid  354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...
4       Gasoline                         2.0L I4 16V GDI DOHC Turbo

        transmission                 ext_col int_col  \
0        6-Speed A/T                   Black   Black
1  8-Speed Automatic         Moonlight Cloud    Gray
2          Automatic                    Blue   Black
3        7-Speed A/T                   Black   Black
4  8-Speed Automatic  Glacier White Metallic   Black

                                 accident clean_title    price capacity
0  At least 1 accident or damage reported         Yes  $10,300     3.7L
1  At least 1 accident or damage reported         Yes  $38,005     3.8L
2                           None reported         NaN  $54,598      NaN
3                           None reported         Yes  $15,500     3.5L
4                           None reported         NaN  $34,999     2.0L

In [119]:
data['price'] = data['price'].replace({'\$':'',',':''}, regex = True)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17832\1145536777.py:1: SyntaxWarning: invalid escape sequence '\$'
  data['price'] = data['price'].replace({'\$':'',',':''}, regex = True)

In [121]:
data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,capacity
0,Ford,Utility Police Interceptor Base,2013,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300,3.7L
1,Hyundai,Palisade SEL,2021,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005,3.8L
2,Lexus,RX 350 RX 350,2022,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500,3.5L
4,Audi,Q3 45 S line Premium Plus,2021,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999,2.0L