## Arrays

In [10]:
import numpy as np
a=np.array([1,2,3]) 
print(type(a), a.shape, a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]

In [20]:
a = np.ones((1,2)) #create an array of all ones
print(a)

[[1. 1.]]

In [22]:
b = np.eye(2) #create 2x2 identity matrix
print(b)

[[1. 0.]
 [0. 1.]]

In [24]:
c = np.random.random((2,2))
print(c)

[[0.03380942 0.57481342]
 [0.89618249 0.46666613]]

In [28]:
d = np.zeros((1,3))
print(d)

[[0. 0. 0.]]

## Boolean array indexing

In [31]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2) 
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]

In [33]:
print(a[bool_idx])

[3 4 5 6]

In [35]:
print(a[a>2])

[3 4 5 6]

## Datatypes

In [40]:
x=np.array([1,2])
y=np.array([1.0,2.0])
z=np.array([1,2], dtype=np.int64)
print(x.dtype,y.dtype,z.dtype)

int32 float64 int64

## Array math

x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[1,2],[3,4]], dtype = np.float64)

print(x+y)

In [49]:
#Element wise product; both produce the array
print(x*y)
print(np.multiply(x,y))

[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  4.]
 [ 9. 16.]]

In [51]:
#Element wise divide; both produce the array
print(x/y)
print(np.divide(x,y))

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]

In [53]:
#Element wise square root; both produce the array
print(x*y)
print(np.sqrt(x,y))

[[ 1.  4.]
 [ 9. 16.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]

##  Dot product

In [56]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

#Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v,w))

219
219

we can also use @ operator  which is equivaltent to numpy's dot operator

In [58]:
print(v @ w)

219

## Performance computing on arrays

In [63]:
x = np.array([[1,2],[3,4]])

print(np.sum(x)) #compute sum of all elements
print(np.sum(x, axis=0)) #compute sum of each row
print(np.sum(x, axis=1)) #compute sum of each column

10
[4 6]
[3 7]

In [65]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]

## Broadcasting in NumPy

In [72]:
# we will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) #Create an empty matrix with the same shape as x

# add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

## Tile up

In [81]:
vv = np.tile(v, (4,1)) # stack 4 copies of v on each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

## Logspace

Generate evenly spaces numbers on a log scale.

np.logspace(start,stop,num=50,endpoint=True, base=10.0,dtype=None,axis=0)

Important params
start: starting value of the sequence
end: last value of the sequence
endpoint: if True, the last sample will be included in the sequence
base: the base of the log space. default is 10

In [84]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

## Digitize

bins: array of bins
right: indicates whether the interval includes the right or left bin edge

In [92]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 1.5, 1.6, 4.7, 5.3])
bins = np.array([0, 1, 2, 3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 2, 2, 4, 4], dtype=int64)

## Expand Dimensions

It is used to expand the dimensions of an array. This method is useful for creating sample test data for testing a machine learning model.

np.expand_dims(a, axis)

In [101]:
arr = np.array([8, 14, 1, 8, 11, 4, 9, 4, 1, 13, 13, 11])
np.expand_dims(arr, axis=0)

array([[ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11]])

In [103]:
np.expand_dims(arr, axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [ 1],
       [13],
       [13],
       [11]])

## Squeeze

Reduce the dimension of an array by removing single-dimension entire
 np.squeeze(a, axis=None)

In [108]:
arr = np.array([[8], [14], [1], [8], [11], [4], [9], [4], [1], [13], [13], [11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

## Count Non-Zero

Count all the non-zero elemens and return their count
 np.count_nonzero(a, axis= None, ,  keepdims=False)

In [116]:
a = np.array([0,0,1,1,3])
np.count_nonzero(a)

3

## argwhere

a = np.array([0,0,1,1,3])
np.argwhere(a)

## argmax & arg

In [121]:
arr = np.array([[0.12, 0.64, 0.19, 0.05]])
np.argmax(arr)

1

arg min will return the index of the lowest element from the array
np.argmin(a, axis=None, out=None)
np.argmax(a, axis=None, out=None)

In [127]:
np.argmin(arr)

3

## sort

sort the array and return

np.sort(a, axis=-1, kind=None, order=None)

Important params
kind: sorting algorithms to use : quicksort, mergesort, heapsort, stable

In [158]:
arr = np.array([2, 5, 7, 1])
np.sort(arr)

array([1, 2, 5, 7])

## Abs

return the absolute values of the elements inside an array. it is useful when an array contains negative values.

In [161]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

## Round

Round the float values to a specified number of decimal points

np.round(a, decimals=0, out=None)

decimals : number  of decimal points to keep

In [164]:
a = np.random.random(size=(3,4))
a

array([[0.48020806, 0.31042463, 0.49175195, 0.68279849],
       [0.09480658, 0.56540804, 0.1745372 , 0.64892422],
       [0.45833665, 0.18782846, 0.96987515, 0.18246515]])

In [166]:
np.round(a, decimals=0)

array([[0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.]])

In [168]:
np.round(a, decimals=1)

array([[0.5, 0.3, 0.5, 0.7],
       [0.1, 0.6, 0.2, 0.6],
       [0.5, 0.2, 1. , 0.2]])

## Clip

It is used to keep the values of an array within a range

In [182]:
arr= np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [184]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [186]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

## Where

Return elements from an array where a condition satisfies
np.where(condition, [x,y])

Important params
condition:

In [190]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [192]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [194]:
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

## Put

replaces specified elements of an array with given values

np.put(a, ind, v)

Important params
a: array
ind: indicies to be replaced
v: values to place

In [199]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [201]:
np.put(arr,[1,2], [6,7])
arr

array([1, 6, 7, 4, 5, 6])

## Copyto

Copy the content of aone array into another

copyto(dst, src, casting='same_kind', where=True)

Important params:
dst: array into which values are copied
src: array from which values are copied

In [211]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Before arr1", arr1)
print("Before arr2", arr1)
np.copyto(arr1, arr2)
print("After arr1", arr1)
print("After arr2", arr2)

Before arr1 [1 2 3]
Before arr2 [1 2 3]
After arr1 [4 5 6]
After arr2 [4 5 6]

## Extracts unique elements from both arrays

setxor1d function will return all the unique values from both arrays in second order

In [217]:
a = np.array([1,2,3,4])
b = np.array([1,2,9,8])
np.setxor1d(a,b)

array([3, 4, 8, 9])

## Splitting

## Horizontal Split

hsplit function will split the data horizontally into n equal parts

In [221]:
A = np.array([[3,4,5,2], [6,7,2,6]])
np.hsplit(A, 2)  # splis the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [225]:
np.hsplit(A,4) ## splis the data into four equal parts

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

## Vertical Split

vsplit will split the data vertically into n equal parts

In [232]:
 A = np.array([[3,4,5,2], [6,7,2,6]])
np.vsplit(A, 2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

## Comparing Two Arrays

## allclose

In [237]:
a = np.array([0.25, 0.4, 0.6, 0.32])
b = np.array([0.26, 0.3, 0.7, 0.32])
tolerance = 0.1
np.allclose(a,b,tolerance)

False

In [239]:
tolerance = 0.5
np.allclose(a,b,tolerance)

True

## Repeat

it is used to repeat elements of an array for n number of times

np.repear(a, repeats, axis=None)

a: element to repeat
repeats: number of times to repeat element

In [244]:
np.repeat('2017', 3)

array(['2017', '2017', '2017'], dtype='<U4')

In [246]:
import pandas as pd

In [252]:
fruits = pd.DataFrame([
    ['Mango', 40],
    ['Apple' , 50],
    ['Banana', 130]
    ], columns=['Product', 'ContainerSales'])
fruits

  Product  ContainerSales
0   Mango              40
1   Apple              50
2  Banana             130

In [254]:
fruits['year'] = np.repeat(2020, fruits.shape[0])
'''
Above code will repeat the year 2020 n times, where n is the length of data
'''
fruits

  Product  ContainerSales  year
0   Mango              40  2020
1   Apple              50  2020
2  Banana             130  2020

## Array Printing options

## Show Floats with two decimal values

In [259]:
np.set_printoptions(precision=2)
a=np.array([12.23456, 32.345335])
print(a)

[12.23 32.35]

## Prints Array to its max

In [264]:
np.set_printoptions(threshold=np.inf)

## Increase the number of elements in a line

In [269]:
np.set_printoptions(linewidth=100) ## Default 75